name: CI/CD
on:
  push:
    branches: ["main"]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: jorgebruned.com
      url: ${{ vars.WEB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: make init_py
      - name: Generate icon font
        run: make font
      - name: Build site
        run: make build
      - name: Render PDF
        run: make pdf
      - name: Publish via FTP
        run: make publish
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_PATH: ${{ secrets.FTP_PATH }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_PUBKEY: ${{ secrets.FTP_PUBKEY }}
          IGNORED_PATHS: ${{ secrets.IGNORED_PATHS }}
